name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: . # or path/to/artifact
